### ISSUE TITLE
did the ldap authentication truly happen?

### ISSUE THREAD

**Issue by runozo** [NaturalHistoryMuseum/ckanext-ldap#1]
Working with CKAN 2.3 I'm trying to debug ldap authentication  with Python pdb.

Following the flux from /src/ckan/ckan/controllers/user.py login():

``` python
def login(self, error=None):
    # Do any plugin login stuff
    for item in p.PluginImplementations(p.IAuthenticator):
        item.login()
        ....
```

So, when it calls item.login(), the code executed in the plugin is:

``` python
def login(self):
    """Implementation of IAuthenticator.login

    We don't need to do anything here as we override the form & implement our own controller action
    """
    pass
```

Meaning that the authentication against ldap will never happen.
Am I missing something here, or is it a bug?

Thank you

**Comment by aliceh75** [comment]
Hi,

Hopefully the fact there is a comment stating nothing happens there should indicate this was done on purpose ;)

The [ckan docs on IAuthenticator](http://docs.ckan.org/en/943-writing-extensions-tutorial/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IAuthenticator) are not very clear on the topic, and [neither is the code](https://github.com/ckan/ckan/blob/master/ckan/plugins/interfaces.py#L1408), but the `login` method of `IAuthenticator` is something that is called once the user has logged in, to allow plugins to react to that. It's not something that is called to process the username or password (as you can see, the method does not have any parameters).

`identify` is called to check which is the current user, and `logout` once the user has logged out. But the actual work happens elsewhere. This is what happens:
- `ckanext-ldap` overrides the login form. This is done by adding a custom [templates/user/login.html](https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/master/ckanext/ldap/templates/user/login.html) which ckan will pick up automatically.
- The important difference of the new template is that [it uses ldap_logging_handler as the form action](https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/master/ckanext/ldap/templates/user/login.html#L14);
- `ldap_logging_handler` is [routed](https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/master/ckanext/ldap/plugin.py#L39) to the [UserController](https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/master/ckanext/ldap/controllers/user.py#L24) in `controllers/user.py`. This is where the actual work is done.

So how can you test it's working?
- Ensure that your logging request are sent to `ldap_logging_handler` when the form is submitted (Firefox/Chrome network inspector will easily allow you to see that);
- Put a break point in [UserController.login_handler](https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/master/ckanext/ldap/controllers/user.py#L25) and see what happens;
- Check your log files.If `ckanext-ldap` is invoked, then it will log any error that is encountered.

Let me know if you have any other problems.

**Comment by runozo** [comment]
Thank you very much for answering.

I did attempted to put a breakpoint in UserController.login_handler but, doing the login process, it never fires, it did only in [plugin.py:login()](https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/master/ckanext/ldap/plugin.py#L94)
In the logs also there's nothing related to ckanext-ldap.
Now I'm wondering if I missed something important in the configuration.

For the breakpoint I did like this:

```python
class UserController(p.toolkit.BaseController):

    def login_handler(self):
        """Action called when login in via the LDAP login form"""
        import pdb
        pdb.set_trace()
        params = request.POST
```
My relevant config:

```
ckan.plugins = datastore stats text_view image_view recline_view harvest ckan_harvester spatial_metadata spatial_query recline_preview ldap

ldap.uri = ldap://xxx.xxx..net
ldap.base_dn = DC=xxx,DC=xxx,DC=net
ldap.search.filter = sAMAccountName={login}
ldap.username = sAMAccountName
ldap.email = mail
ldap.ckan_fallback = true
ldap.auth.dn = xxxxxx
ldap.auth.password = xxxxxxx
ldap.organization.id = xxxx
```

thank you again  and sorry for bothering

**Comment by runozo** [comment]
Thank you very much for answering and pointing the right direction :)
My login_handler never fires, cause I have the "wrong" login form.
Should I change it manually (how?), or it's meant to be automatically picked from ckan and it's mine that doesn't work?

Thanks again

**Comment by aliceh75** [comment]
Hi,

It should be picked up automatically. The ckan documentation explains how overriding templates work:
http://docs.ckan.org/en/latest/theming/templates.html#replacing-a-default-template-file

Try the following:
- Add `debug = True` in your ckan .ini file;
- On the login page you will see a link called 'debug' in the footer. Clicking on that will provide information on the current template.

If it picked up the right template, the path should be something like : `.../ckanext-ldap/ckanext/ldap/templates/user/login.html`

**Comment by aliceh75** [comment]
Ha, I think I see the problem. How did you install `ckanext-ldap` ? If you did a `pip install` or a `python setup.py install` then the template file won't have been included (which would be a bug - once we confirm this is the problem, I will fix it!).

To confirm this theory, can you try to uninstall ckanext-ldap, then re-install it in development mode.
1. If you installed it using pip:
   
   ``` bash
   pip uninstall ckanext-ldap 
   pip install -e git+https://github.com/NaturalHistoryMuseum/ckanext-ldap.git#egg=ckanext-ldap
   ```
2. If you installed using setup.py:
   
   ``` bash
   pip uninstall ckanext-ldap
   python setup.py develop
   ```
