### ISSUE TITLE
CKAN with LDAP and Cosign (SSO)

### ISSUE THREAD

**Issue by adrianfish** [NaturalHistoryMuseum/ckanext-ldap#10]
Hi, I'm using CKAN with Apache and an SSO system called Cosign. Cosign works as an authenticator in Apache and ends up setting REMOTE_USER before the python code fires up. What I'm trying to do is use LDAP user lookup based on that preset REMOTE_USER. Can I do that with this? Any advice greatly appreciated - I'm a Python novice.

**Comment by alycejenni** [comment]
Closing due to issue age - if this is still relevant, feel free to reopen/open a new issue.
