### ISSUE TITLE
Error with 2.10.3

### ISSUE THREAD

**Issue by t-book** [NaturalHistoryMuseum/ckanext-ldap#131]
Hi,

I get 

AttributeError: 'LdapPlugin' object has no attribute 'authenticate'

with ckan 2.10.3. Can one confirm that the plugin is working in this latest version?

Thanks,

– Toni

**Comment by alycejenni** [comment]
We haven't tested it on 2.10 yet so I'm not sure, but I wouldn't be surprised if it was broken in the new version.
This probably relates to #104

**Comment by t-book** [comment]
Oh hello @alycejenni . thanks for your fast reply ;)
So it looks the plugin needs the authenticate method. Find here my quick test.

https://github.com/NaturalHistoryMuseum/ckanext-ldap/compare/main...cuprit-gbr:ckanext-ldap:main

I'm not really familiar with iAuthenticator interface. 

Anyways. Hopefully it helps you to know that it is working with a simple fix. Even if it is not perfect.

**Comment by jrdh** [comment]
Fix is merged into dev, we'll do a release next week but do feel free to check the dev branch's latest changes if you want to confirm the fix works for you @t-book. As I mentioned in #132 and you highlighted in your comment above, this isn't the ideal fix, doing #104 would be best. It's on our backlog and we'll try to find the time to look at it soon.
