### ISSUE TITLE
CKAN 2.6 + Active Directory

### ISSUE THREAD

**Issue by rotragit** [NaturalHistoryMuseum/ckanext-ldap#15]
Hi all,
I'm really sorry, but I'm unable to let the plugin run against active directory. I'm sure it's a configuration problem, My config is:

ckanext.ldap.uri = ldap://my.ldap.srv:389
ckanext.ldap.base_dn = dc=ds,dc=units
ckanext.ldap.search.filter = sAMAccountName={login}
ckanext.ldap.username = sAMAccountName
ckanext.ldap.email = email
ckanext.ldap.ckan_fallback = true
ckanext.ldap.prevent_edits = false
ckanext.ldap.auth.dn = cn=BIBLIO,dc=ds,dc=units
ckanext.ldap.auth.password = password
ckanext.ldap.fullname =
ckanext.ldap.about =
ckanext.ldap.organization.id = units
ckanext.ldap.organization.role = member
ckanext.ldap.search.alt =
ckanext.ldap.search.alt_msg = 'Please use your short account name instead'

The error I get is 

[Wed Nov 09 11:44:42.540154 2016] [wsgi:error] [pid 9530] [remote 127.0.0.1:38947]   log.error('LDAP query failed. Maybe you need auth credentials for performing search
es? Error returned by the server: ' + e.info)

ckanext.ldap.auth.dn = cn=BIBLIO,dc=ds,dc=units
ckanext.ldap.auth.password = password

are verified to be ok.

Somebody can help me?
Thank you!
Romano

**Comment by johnwchen** [comment]
My setup is pretty much the same.. I am getting the following error.

 [ckanext.ldap.controllers.user] LDAP server credentials (ckanext.ldap.auth.dn and ckanext.ldap.auth.password) invalid

I have confirmed that I could query AD with the same set of credential (ckanext.ldap.auth.password)  and  dn (ckanext.ldap.auth.dn). I  am able to see that it is reaching our LDAP (AD) server as well.... but when logging in ..i get the invalid error message.

Anyone has a working same of AD configuration file that they could share?

**Comment by rotragit** [comment]
Hi,
my production settings have only this difference from the above:

ckanext.ldap.search.filter =  (sAMAccountName={login})

I don't know if this difference is important or not, but my system is
running now.

romano

**Comment by johnwchen** [comment]
I got it working now.. seem to be a spacing issue.  I have another issue now.. when I have "ckanext.ldap.base_dn = dc=example,dc=com", it does't work.  But when i put "ckanext.ldap.base_dn = Ou=users,dc=example,dc=com", it works, BUT, it doesn't see all the user in AD.. only some.. Anyone have a idea ?

**Comment by rotragit** [comment]
That's a name lookup problem. I suggest to try with ldapsearch tool to
debug.

Il 11 ott 2017 4:45 PM, "johnwchen" <notifications@github.com> ha scritto:

**Comment by johnwchen** [comment]
we have other apps that points to the same ldap server it works as expected... strange why this is not working.  BTW - does this plugin support AD group query?  I would like to us a group instead of it querying the entire AD structure

**Comment by alycejenni** [comment]
I know this is a very old issue, but for anyone who finds this later: I believe you can query a group by using a search filter like `(sAMAccountName={login})(memberOf=cn=GROUPNAME,ou=USERS,dc=EXAMPLE,dc=com)`. Basically, use the LDAP filter.
