### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by hvwaldow** [NaturalHistoryMuseum/ckanext-ldap#18]
@benscott please excuse the intrusive demonstration, but I suspect I my email did not reach you.
Login and have a look at your private datasets: 
http://data.nhm.ac.uk/user/bens3

**Comment by benscott** [comment]
Thanks for raising this critical issue  fixed in https://github.com/NaturalHistoryMuseum/ckanext-ldap/commit/1e9e56f052782d9cd807717d52dfb55f7bfd5d3c
