### ISSUE TITLE
Question: difference between this plugin and the repoze.who.ldap plugin

### ISSUE THREAD

**Issue by marcesher** [NaturalHistoryMuseum/ckanext-ldap#2]
Hey all,

I'm researching different ways to authenticate  CKAN against Active Directory. Can you say how this ckanext-ldap plugin differs from this repoze.who.plugins.ldap  http://code.gustavonarea.net/repoze.who.plugins.ldap/Using.html, with respect to using them in CKAN?

thanks!

**Comment by aliceh75** [comment]
There are two approaches to writing a CKAN authentication plugin - one is to use [repoze.who](https://repozewho.readthedocs.org/en/latest/), the other is to write a CKAN plugin that implements the [IAuthenticator](http://docs.ckan.org/en/ckan-2.3/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IAuthenticator) interface.

We needed custom functionality (for example, _ckanext-ldap_ will optionally add newly created users to a given organization), so whichever approach we took required some development on our part. Given that ckan developers themselves go for the IAuthenticator approach (see https://github.com/ckan/ckanext-persona or https://github.com/ckan/ckanext-oauth2waad for example), we decided to follow that approach as well. [This email](https://lists.okfn.org/pipermail/ckan-dev/2014-June/007727.html) from Sean Hammond (who is a Ckan core commiter) also suggests IAuthenticator is the prefered approach.

It is not entirely clear to me how _repoze.who_ would work - _repoze.who_ is a middleware authentication tool - but I'm not certain it will create users as well. For a user to use Ckan, they need a local user account - regardless of how the authentication happened. So when a user logs in using _ckanext-ldap_ for the first time, a Ckan account is automatically created to match that Ldap user. I'm not sure how that would be handled using _repoze.who_.

If you do decide to look into _repoze.who_ approach, please let us know the differences so we can add them to the documentation! 

(If you decide to try _ckanext-ldap_ now, there seems to be an issue (#1) - until I can confirm the issue and fix it, try to install it in development mode (ie. `pip install -e ...` or `python setup.py develop`)

**Comment by marcesher** [comment]
@aliceh75  Thanks! Your comments help a ton.

**Comment by marcesher** [comment]
@aliceh75 Reading through the source, it looks like you're skipping the ckan user table entirely and using your own. Does this mean that if we used your plugin, we could also use email addresses as usernames, which we can't do now b/c of ckan's restrictions against punctuation in usernames?

Thanks again.

**Comment by aliceh75** [comment]
We do use the ckan user table - I don't think it's possible not to.

If you look at https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/master/ckanext/ldap/controllers/user.py#L160 you will see we invoke `user_create`.

However the plugin does not use the login name as the ckan username. The login name is the one in the ldap database - and the plugin generates a unique ckan username based on that. This is why the plugin also saves data in it's own table - to be able to associate ldap credentials with ckan user name, as we cannot guarantee there will be a one-to-one mapping between the two. You can see the code that generates the ckan username from the ldap username here: https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/master/ckanext/ldap/controllers/user.py#L111 - but remember this is used internally, not at the login prompt.

The plugin allows you to configure which credentials people enter at the login prompt. This is defined by the `ldap.search.filter` setting. If using Exchange, you can set that to the short windows user name by entering `sAMAccountName={login}`. And if you want to use the email as the primary login instead, you can set that to (if using Exchange) `mail={login}`

The plugin even allows you to have alternative logins. We use this to mimick Window's login where users can login using either their short user name or full user name. So if you wanted, say, to allow users to login either using their email or their full user name that would be possible too (see the configuration options).

**Comment by marcesher** [comment]
excellent. Thanks again!

**Comment by marcesher** [comment]
@aliceh75 My colleague @ooblioob and I want to thank you again for your work here. We were able to get ckanext-ldap going with no fuss, and it works great. Kudos for great software and great docs!
:trophy:
