### ISSUE TITLE
Time Out Setting

### ISSUE THREAD

**Issue by johnwchen** [NaturalHistoryMuseum/ckanext-ldap#26]
Is there a time-out setting ?  I have enable the AD-LDAP authentication, but user are never kicked off or logged off.  Is it possible to force a time out value on users?  Before the integration user was getting logged off after certain time-out. based on local authentication

**Comment by jrdh** [comment]
I think this would be something you'd need to configure outside of this extension as this extension just provides authentication, not session management after a user has been authenticated.
