### ISSUE TITLE
Set action = h.get_login_action() doesn't work

### ISSUE THREAD

**Issue by ashleysommer** [NaturalHistoryMuseum/ckanext-ldap#36]
This is an error introduced with the PR that landed 6 days ago: https://github.com/NaturalHistoryMuseum/ckanext-ldap/commit/94d7f3290edc1adac01da88d21e0fd79ac0d71f1

Specifically this snippet:
```
{% set action = h.get_login_action() %}
{% block form %}
  {% snippet "user/snippets/login_form.html", action=action, error_summary=error_summary %}
{% endblock %}
```
I've run it with python debugger attached, although `get_login_action()` returns the correct string ("/ldap_login_handler"), for some reason the `action` variable gets set to `""`.

That ends up rendering the login_form.html snippet with `action=""`.

If I run this:
```
{% set action = h.get_login_action() %}
{% block form %}
  <p>"{{ action }}"</p>
  {% snippet "user/snippets/login_form.html", action=action, error_summary=error_summary %}
{% endblock %}
```
I see `<p>""</p>`.

If I run this:
```
{% set action = "Hello" %}
{% block form %}
  <p>"{{ action }}"</p>
  {% snippet "user/snippets/login_form.html", action=action, error_summary=error_summary %}
{% endblock %}
```
I see `<p>""</p>`.

If I run this:
```
{% set a = "Hello" %}
{% block form %}
  <p>"{{ a }}"</p>
  {% snippet "user/snippets/login_form.html", action=a, error_summary=error_summary %}
{% endblock %}
```
I see `<p>"Hello"</p>`.

If I run this:
```
{% set a = h.get_login_action() %}
{% block form %}
  <p>"{{ a }}"</p>
  {% snippet "user/snippets/login_form.html", action=a, error_summary=error_summary %}
{% endblock %}
```
I see `<p>"/ldap_login_handler"</p>`.

It seems that there is something about the `action` variable name that is causing the error. Perhaps it is a reserved name, or maybe it is because it is the same name as the parameter to the snippet.

I originally thought it was a Jinja2 version issue, because I was using the default Jinja2 v2.8.0 from the CKAN 2.7.4 requirements.txt. I tried upgrading to v2.9.0, v2.9.3, v2.9.6, and finally to v2.10.0, but all versions give the same error. Is there a specific version of Jinja2 that this is supposed to be used with?

**Comment by ashleysommer** [comment]
I've found two different fixes:

Just use a different variable name, as per my code above.
```
{% set ldap_action = h.get_login_action() %}
{% block form %}
  {% snippet "user/snippets/login_form.html", action=ldap_action, error_summary=error_summary %}
{% endblock %}
```
Or move the variable inside the block. For some reason this fixes the issue too:
```
{% block form %}
  {% set action = h.get_login_action() %}
  {% snippet "user/snippets/login_form.html", action=action, error_summary=error_summary %}
{% endblock %}
```
Its some weird scope issue, I think. I've written a PR with the first stated fix.

**Comment by jrdh** [comment]
That is an odd one isn't it? Thanks for spotting and fixing!
