### ISSUE TITLE
User login sessions no longer time-out after installation of CKAN LDAP

### ISSUE THREAD

**Issue by ply112** [NaturalHistoryMuseum/ckanext-ldap#38]
User logins on CKAN (v2.6.1) should time out in accordance to the time-out parameter set in the configuration file.  It worked before the CKAN LDAP plugin.  After the LDAP installation, user logins no longer time out even though the time-out parameter in the configuration file remained unchanged.  Is there a way to get around this problem?

**Comment by jrdh** [comment]
Hi @ply112, I've just tested this against CKAN v2.3a and the timeout setting worked fine for me, how are you configuring the timeout setting?

**Comment by ply112** [comment]
We set the timeout parameter in the configuration file of CKAN, and it worked fine for user accounts created within CKAN.  LDAP doesn't seem to use this timeout parameter.  Do you have any clue? Thanks.

**Comment by jrdh** [comment]
After a bit more looking I can get it to work by using the session timeout defined through beaker but not through the repoze related config settings. So if I use `who.timeout = #` it doesn't work but if I use `beaker.session.timeout = #` it does work. I've had a look through the doc and various PRs related to this functionality and it's not exactly clear whats going on though they refer to `who.timeout = #` as the way to do it which I assume is what you tried. I'll keep digging to see if I can work out what's going on, my guess would be that we're impacting the config in some way.

**Comment by ply112** [comment]
Thank you so much.  I thought I had tried the beaker.session.timeout as well but it didn't seem to work, but I could be wrong.  I'll give it a try again tomorrow when I'm at work.  Thanks again.

**Comment by ply112** [comment]
The configuration file didn't have a beacker.session.timeout parameter.  After adding it, timeout now works.  Thanks, jrdh.
