### ISSUE TITLE
api/3/action/help_show?name=datastore_search", "success": false, "error": {"message": "Internal Server Error", "__type": "Internal Server Error"}}

### ISSUE THREAD

**Issue by CristianoMarquesPoa** [NaturalHistoryMuseum/ckanext-ldap#41]
After install upgrade ldap for 2.8a, the function datastore_search fail the execution.

api/3/action/help_show?name=datastore_search", "success": false, "error": {"message": "Internal Server Error", "__type": "Internal Server Error"}}

**Comment by jrdh** [comment]
Hi @CristianoMarquesPoa, are you working off master or are you working off the 2.8.x branch? This issue has some more details: https://github.com/NaturalHistoryMuseum/ckanext-ldap/issues/40
