### ISSUE TITLE
Please guide me how to use this repository for ldap configuration

### ISSUE THREAD

**Issue by vinga2805** [NaturalHistoryMuseum/ckanext-ldap#43]
Hi,
I planning to configure  SSON through LDAP authentication for CKAN on Amazon Linux.

I am following below steps.
1.Added below parameters in production.ini file.

```
ckanext.ldap.uri = ******
ckanext.ldap.auth.dn = "CN=****,CN=*****,DC=***,DC=****,DC=***”
ckanext.ldap.auth.password = ******
ckanext.ldap.base_dn = OU=****,DC=corp,DC=*****,DC=***
ckanext.ldap.search.filter = ***={login}
ckanext.ldap.username = *****
ckanext.ldap.email = ***
ckanext.ldap.ckan_fallback = True
```

2. Also added below plugins in the same file.

```
ckan.plugins = stats text_view image_view recline_view datastore datapusher resource_proxy geo_view pages harvest ckan_harvester ckanext-ldap ldap
```

3. Installed dependent python packages.

```
pip install python-ldap
sudo yum install python-devel openldap-devel
```

4.Ran below command.

```
paster --plugin=ckanext-ldap ldap setup-org -c /etc/ckan/default/production.ini
```

Which ran into below failures.

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib64/python2.7/site-packages/paste/script/command.py", line 91, in run
    commands = get_commands()
  File "/usr/lib/ckan/default/local/lib64/python2.7/site-packages/paste/script/command.py", line 133, in get_commands
    plugins = pluginlib.resolve_plugins(plugins)
  File "/usr/lib/ckan/default/local/lib64/python2.7/site-packages/paste/script/pluginlib.py", line 83, in resolve_plugins
    pkg_resources.require(plugin)
  File "/usr/lib/ckan/default/local/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 971, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/ckan/default/local/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 857, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: <exception str() failed>
```

Please help me here I dont know where i am doing wrong.
Your help in this matter would be highly appreciated.

Thanks and Regards,
Vishal Ingale

**Comment by jrdh** [comment]
Looks like this is something to do with your environment setup, perhaps https://github.com/ckan/ckan/issues/2865 might help?

**Comment by vinga2805** [comment]
> Looks like this is something to do with your environment setup, perhaps [ckan/ckan#2865](https://github.com/ckan/ckan/issues/2865) might help?

It would be great if you can provide me steps to install ckanext-ldap because Readme file is not very clear to me.

**Comment by vinga2805** [comment]
its getting annoyed day by day.
I have been trying to configure since last 3 days but no luck.
can anyone help me with this extension?
Now I have started getting no db module error

**Comment by alycejenni** [comment]
Can you post the error messages for the new error please?

**Comment by alycejenni** [comment]
This doesn't appear to be anything to do with our LDAP plugin, and is now inactive, so I'm closing. You can reopen or create a new issue if you have problems with the plugin later.
