### ISSUE TITLE
ckanext.datastore.db does not exist

### ISSUE THREAD

**Issue by frafra** [NaturalHistoryMuseum/ckanext-ldap#45]
The `README.md` file suggest to run this command:

`paster --plugin=ckanext-ldap ldap setup-org -c /etc/ckan/default/development.ini`

`ckanext/ldap/commands/ldap.py` tries to import `ckanext.datastore.db` which does not exist in CKAN 2.7 and CKAN 2.8.

**Comment by alycejenni** [comment]
The master branch is currently targeting version 2.3. The ckan-upgrade-2.8.0a branch may help you - it's not completely done but a lot of those sorts of bugs have been fixed.

**Comment by frafra** [comment]
Sorry, ok, thank you :-)
