### ISSUE TITLE
Cache on server (LDAP)

### ISSUE THREAD

**Issue by aldo2102** [NaturalHistoryMuseum/ckanext-ldap#53]
On my server, when a user logs on, when another user logs on to another computer, it appears that they are logged in the profile of the person who logged in first. I think it might be something in the server cache, because when I clear the server cache it is possible to log in again, but the problem repeats itself.

**Comment by lucasbenevides** [comment]
Hello Aldo,

In my environment we are also experiencing this issue. It looks like the
upper bar doesn't get the real informations, it looks as it reads from the
server cache. The button to Logout doesn't work everytime, althout
sometimes it does.

Anyone else is having this trouble?

Lucas Benevides

Em ter, 9 de abr de 2019 às 17:16, aldo2102 <notifications@github.com>
escreveu:

**Comment by boykoc** [comment]
@lucasbenevides @aldo2102 my comments over on [issue 40](https://github.com/NaturalHistoryMuseum/ckanext-ldap/issues/40#issuecomment-485869920) might be helpful but i'm still digging a little.

**Comment by aldo2102** [comment]
> @lucasbenevides @ aldo2102 meus comentários sobre o [problema 40](https://github.com/NaturalHistoryMuseum/ckanext-ldap/issues/40#issuecomment-485869920) podem ser úteis, mas ainda estou cavando um pouco.

Can solve the problem.

When we checked the NGINX settings (/etc/nginx/sites-available/ckan), we modified it to look like this:

server {
    client_max_body_size 100M;
    location / {
        proxy_pass http://127.0.0.1:8080/;

        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-re$
        if_modified_since off;
        expires off;
        etag off;
        # In emergency comment out line to force caching
        # proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
    }

}



As a result, the cache problem has been fixed.

**Comment by boykoc** [comment]
@aldo2102 can you explain a bit of what you're doing with this change? It kind of looks like you're turning off caching by overriding the cache-control header (but im not an nginx config expert)?   If so, you could remove nginx altogether from a cache perspective. But ideally the application would be passing the proper headers to enable caching.

**Comment by jrdh** [comment]
This was resolved by removing/limiting the caching in nginx - it's not a problem with this extension, it's a configuration issue in the way CKAN is deployed.
