### ISSUE TITLE
Ckan Showing Internal Server Error 500 when enabling Ldap Plugin

### ISSUE THREAD

**Issue by apoorv0612** [NaturalHistoryMuseum/ckanext-ldap#55]
Hi All
I have installed Ckan on Ubuntu 16.04 from this location --> https://docs.ckan.org/en/2.8/maintaining/installing/install-from-package.html
Everything works fine. I want to install Ldap extension on my newly installed CKan. 
I followed the steps given there --> https://extensions.ckan.org/extension/ldap/
my ldap configuration looks like this 
ckanext.ldap.uri = ldap://x.x.x.x:389
ckanext.ldap.auth.password = secret
ckanext.ldap.base_dn = ou=users,dc=example,dc=com
ckanext.ldap.search.filter = abc={login}
ckanext.ldap.username = abc
ckanext.ldap.email = abc@zaq.com

I restarted my apache2 and nginx. Now when i am going to ckan login page it's showing me internal server error i don't know why. Even when i am clicking on about page or register page it's showing internal server error.  I checked logs ( /var/log/apache2/ckan_default.error.log)
Logs are showing  
[wsgi:error] [pid 5687:tid 139923593352960] 2019-05-15 07:01:05,712 INFO  [ckan.config.environment] Loading static files from public
 [wsgi:error] [pid 5687:tid 139923593352960] 2019-05-15 07:01:05,844 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
[wsgi:error] [pid 5687:tid 139923593352960] 2019-05-15 07:01:06,134 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
 [wsgi:error] [pid 5687:tid 139923484149504] 2019-05-15 10:35:10,526 WARNI [ckan.lib.maintain] Function _resource_preview() in module ckan.controllers.package has been deprecated and will be removed in a later release of ckan. Resource preview is deprecated. Please use the new resource views
 [wsgi:error] [pid 5687:tid 139923484149504] 2019-05-15 10:35:10,796 INFO  [ckan.lib.base]  /dataset/claritas-ipa-net-worth-profiles render time 0.294 seconds
[wsgi:error] [pid 5687:tid 139923475748608] 2019-05-15 10:35:13,276 INFO  [ckan.lib.base]  /organization/third-party-data render time 0.217 seconds
 [wsgi:error] [pid 5687:tid 139923484149504] 2019-05-15 10:35:18,047 INFO  [ckan.lib.base]  /organization/third-party-data render time 0.217 seconds
[wsgi:error] [pid 5687:tid 139923484149504] 2019-05-15 10:36:04,726 INFO  [ckan.lib.base]  /dataset render time 0.155 seconds

I have googled it these errors but not able to find any proper solution.
I even tried running paster serve but it also doesn't throw any error. 
Any idea how to solve this ? I am stuck on this issue for past 2 days

**Comment by alycejenni** [comment]
Sorry this didn't get answered at the time! That documentation is very outdated - you'll probably have more luck with the README on this repository because it's more recent and well maintained.
