### ISSUE TITLE
ckanext.ldap.organization.role documentation assumes ckanext.ldap.organization.id

### ISSUE THREAD

**Issue by Chealer** [NaturalHistoryMuseum/ckanext-ldap#60]
[The configuration documentation's _Other options_ sub-section](https://github.com/NaturalHistoryMuseum/ckanext-ldap#other-options) has the following description for ckanext.ldap.organization.role:

> The role given to users added in the given organization ('admin', 'editor' or 'member'). Warning: Changing this parameter will only affect users that have not yet logged on. It will not modify the role of users who have already logged on.

At first sight this seems to say the value must indicate both an organization and a role given, but that seems improbable as no format is indicated. After looking at the section as a whole, it appears that option must assume that option ckanext.ldap.organization.id was set. I assume "the given organization" refers to the organization which ckanext.ldap.organization.id indicates.

**Comment by alycejenni** [comment]
The `role` option only gets used if `id` is set:

https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/b510aae2077cf0eb5068a72effed81dcd5b225c1/ckanext/ldap/routes/_helpers.py#L176

But that wasn't clear in the README, and the default value was also missing. I've added the default and clarified that `id` is required for the `role` to be used.

Thank you for pointing this out!

**Comment by Chealer** [comment]
Thank you @alycejenni that solves the problem. It would be extra clear if "The role given to users added in the given organization" would read "The role given to users added in the organization specified using ckanext.ldap.organization.id".
