### ISSUE TITLE
Mapping from LDAP groups to CKAN roles undocumented

### ISSUE THREAD

**Issue by Chealer** [NaturalHistoryMuseum/ckanext-ldap#61]
As the README file does not explain at all how to map groups in LDAP to roles in CKAN, and as the README appears to be the only documentation, I am guessing that ckanext-ldap does not allow defining roles via the LDAP directory.

If support is already present, please document it. If not, please explicitly document that (in the README) until the feature is added.

For what it's worth, [this other LDAP extension](https://github.com/whythawk/ckanext-ldap) does claim a limited mapping from LDAP groups. However, it is probably not compatible with current CKAN versions.

**Comment by alycejenni** [comment]
This is not something this plugin can currently do, and at the moment there are no plans to add it. I've added a quick line in the README to clarify this.

Please feel free to open a pull request if you decide to implement this yourself!

**Comment by Chealer** [comment]
> This is not something this plugin can currently do, and at the moment there are no plans to add it. I've added a quick line in the README to clarify this.

Thank you @alycejenni that mostly solves the problem since those looking carefully should find the information there, but it would be clearer (and faster) to indicate this next to features. The Overview section could have a "Features currently exclude:" list.

> Please feel free to open a pull request if you decide to implement this yourself!

This will not happen in the next weeks, but it might.
