### ISSUE TITLE
CKAN not starting on Ubuntu 20.04 Server, CKAN 2.9.0

### ISSUE THREAD

**Issue by weshinsley** [NaturalHistoryMuseum/ckanext-ldap#64]
First - thank you for writing and maintaining this really useful plugin - very appreciated and we've used it a few years.

Just to accompany https://github.com/NaturalHistoryMuseum/ckanext-ldap/pull/63

Two tiny python 2->3 leftovers are causing CKAN to not start (Internal Server Error) when I enable the latest build of the ldap extension, on a new Ubuntu 20.04 server VM (which defaults to Python 3.8.5), with a build of CKAN 2.9.0 from source. 

The PR #63 fixes both of them, and is now starting up for me with the plugin enabled.

Thanks again

**Comment by jrdh** [comment]
Resolved in https://github.com/NaturalHistoryMuseum/ckanext-ldap/issues/63, thanks again @weshinsley!
