### ISSUE TITLE
Did you create a release in pypi?

### ISSUE THREAD

**Issue by idgserpro** [NaturalHistoryMuseum/ckanext-ldap#7]
I can't find https://pypi.python.org/pypi/ckanext-ldap in Pypi.

![selecao_090](https://cloud.githubusercontent.com/assets/8203476/10616536/5161709e-7744-11e5-871f-4a08fe60274e.png)

My question is: was it ever created? Did you delete it? Or the one in pypi was from https://github.com/whythawk/ckanext-ldap, and now it's deleted?

**Comment by alycejenni** [comment]
This is a staggering 4+ years late (sorry) so I'm answering for people who may find this question later, but as far as I know we've never realised this to pypi. (Yet.)

**Comment by malthe** [comment]
I suppose it would be reasonable to assume that the title here was a mistake and should have read "Are you planning to make a release on PyPi".

**Comment by alycejenni** [comment]
I don't think that was the question at all, but if that's _your_ question - we don't have any specific plans to do so at the moment, but hopefully will in future.
