### ISSUE TITLE
ckanext.ldap.email config not working? (ckanext.ldap.email formatted as sAMAccountName@myorg.org)

### ISSUE THREAD

**Issue by reedv** [NaturalHistoryMuseum/ckanext-ldap#70]
**Description**
Have configs like...
```python
## ckan extensions configs
# ckanext-ldap
ckanext.ldap.uri = ldap://adcontrollerserver.myorg.local:389
ckanext.ldap.base_dn = OU=Central Office,DC=myorg,DC=local
ckanext.ldap.search.filter = sAMAccountName={login}
ckanext.ldap.username = sAMAccountName
ckanext.ldap.email = sAMAccountName@myorg.org
ckanext.ldap.prevent_edits = true
ckanext.ldap.auth.dn = ldapuser
ckanext.ldap.auth.password = xxxxxx
```
... (I do it this way based on what I saw here (https://github.com/NaturalHistoryMuseum/ckanext-ldap/issues/54#issuecomment-493365800) and because our AD users have no "email" attribute) and when trying to log in via AD credentials, seeing errors in the logs like...
```bash
sudo tail -n 20 ckan-*.stderr.log
==> /var/log/ckan/ckan-uwsgi.stderr.log <==
...
ERROR [ckanext.ldap] LDAP search did not return a email.
...
```

**Expected Behaviour**
What you expected to happen instead.
Expected to be able to log in with the AD account used in the CKAN login screen

**To Reproduce**
Steps to reproduce the bug.
1. Install (current) master branch of this extension to CKAN
2. Set configs similarly (specifically the `ckanext.ldap.email` config)
3. Attempt to sign into CKAN with an AD account

**Error Log**
Paste any relevant error logs below:
These _appear_ to be the only relevant logs for this issue:
```bash
sudo tail -n 20 ckan-*.stderr.log
==> /var/log/ckan/ckan-uwsgi.stderr.log <==
...
ERROR [ckanext.ldap] LDAP search did not return a email.
...
```

**Screenshots**
Add screenshots to illustrate the bug if you want.

**Your Setup**
 - CKAN version: 2.9.1
 - Commit/version of this repo: Downloaded from package
 - Browser (if relevant): Chrome

**Anything Else?**
...

**Comment by jrdh** [comment]
The `ckanext.ldap.email` config option should just be the attribute name in your LDAP configuration which can be used to retrieve the user's email address - the readme says: `The LDAP attribute to map to the user's email address.`.

No string interpolation is done, the value of this config option is literally just to extract the user's email from the LDAP response, see the Python LDAP lib doc here https://www.python-ldap.org/en/python-ldap-3.3.0/reference/ldap.html#ldap.LDAPObject.search_s (specifically the `attrlist` which this option will be passed through as part of).

As an example, the value we use at the NHM for this config option is `mail`.

**Comment by jrdh** [comment]
See also the extraction of the value in our code: https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/master/ckanext/ldap/lib/search.py#L138.

**Comment by reedv** [comment]
IC, that code snippet link is helpful, thanks.
Since none of our AD accounts actually have an attribute whose value is the users' email (they all just follow that original interpolated pattern shown), I modified the code in `search.py` like...
```python
# Set return dict
        for i in [u'username', u'fullname', u'email', u'about']:
            cname = u'ckanext.ldap.' + i
            if cname in toolkit.config and toolkit.config[cname] in attr:
                v = attr[toolkit.config[cname]]  # get the value of the attribute named in the ldap ext. configs
                if v:
                    ret[i] = helpers.decode_str(v[0])
                    # my own modification, see issue #70
                    if cname == u'ckanext.ldap.email':
                        ret[i] = helpers.decode_str(v[0] + u'@myorg.org')
```
Ran...
```bash
sudo vim ./ckanext/ldap/lib/search.py
sudo rm -rf  /usr/lib/ckan/default/lib/python2.7/site-packages/ckanext_ldap-*
sudo /usr/lib/ckan/default/bin/python setup.py install
```
...and set the configs like...
```python
## ckan extensions configs
# ckanext-ldap
ckanext.ldap.uri = ldap://adcontrollerserver.myorg.local:389
# I think this can only point to a single OU (ie. can't do multiple OU paths)
ckanext.ldap.base_dn = OU=testgroup,OU=some,DC=myorg,DC=local
ckanext.ldap.search.filter = sAMAccountName={login}
ckanext.ldap.username = sAMAccountName
ckanext.ldap.email = sAMAccountName
ckanext.ldap.prevent_edits = true
ckanext.ldap.auth.dn = ldapuser
ckanext.ldap.auth.password = xxxxxx
ckanext.ldap.search.alt = OU=Central Office,DC=myorg,DC=local
ckanext.ldap.search.alt_msg = Accepted account from Central
```
...and that seemed to work for signing in successfully with the AD accounts.

You could also use extra configs to have an alternative 2-part email format to support such situations like mine here noticing the simple way the `cname` variable seems to be being used here. Would this be a useful pull request?

**Comment by reedv** [comment]
Note from this change that if you switch back to CKAN system users (ie. comment out `ldap` from the plugins in the `ckan.ini` file) it will cause syntax issues. Not totally sure why TBH (not super familiar w/ the CKAN cod base).

See https://github.com/NaturalHistoryMuseum/ckanext-ldap/issues/71
