### ISSUE TITLE
What else is missing?

### ISSUE THREAD

**Issue by mrmm2021** [NaturalHistoryMuseum/ckanext-ldap#76]
We are triyng to  integrate ckan+ldap.
We have a ckan working on docker from keitaro project.
The plugin ckanext-ldap was installed inside the container for testing.
The config was added in production.ini file and ckan is working fine after restart, but we can't see any option to login with ldap.

ckan.plugins = envvars image_view text_view recline_view datastore datapusher ldap

ckanext.ldap.uri = ldap://organization.net:389
ckanext.ldap.auth.dn = CN=user,OU=xxx,OU=xxxx,DC=xxx,DC=net
ckanext.ldap.auth.password = xxxx
ckanext.ldap.base_dn = ou=xxx,dc=xxx,dc=net
ckanext.ldap.search.filter = sAMAccountName={login}
ckanext.ldap.username = sAMAccountName
ckanext.ldap.email = mail

Also, in templates/user/login.html we can't see any ldap option.

What else is missing?

Any help please?

Thanks in advance!

**Comment by jrdh** [comment]
Hi @mrmm2021! ckanext-ldap works by overriding the `templates/user/login.html` template to replace the login action of the button itself (https://github.com/NaturalHistoryMuseum/ckanext-ldap#templates). So you should be able to login with LDAP by just using the normal CKAN login box. If that is failing to log you in then there is likely to be some info in the logs and you can turn on `ckanext.ldap.debug_level` and `ckanext.ldap.trace_level` in your config to see more info. Hope that helps!

**Comment by mrmm2021** [comment]
Hi @jrdh thank you. 
We are unable to login with our AD credentials using default CKAN login box.
We can't see any log entries related to login process in the container log, and the debug level and the trace level have been added to the conf.

"ensure the tables needed by this extension exist."
bash-5.1$ ckan -c /srv/app/production.ini ldap initdb
2021-07-27 13:08:54,751 INFO  [ckan.cli] Using configuration file /srv/app/production.ini
2021-07-27 13:08:54,751 INFO  [ckan.config.environment] Loading static files from public
2021-07-27 13:08:54,903 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2021-07-27 13:08:56,290 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
Table ldap_user already exists

**Comment by mrmm2021** [comment]
Hi,

Following this example:

ckanext.ldap.uri = ldap://ldap.forumsys.com:389
ckanext.ldap.base_dn = dc=example,dc=com
ckanext.ldap.search.filter = cn=*{login}*
ckanext.ldap.username = cn
ckanext.ldap.auth.dn = cn=read-only-admin,dc=example,dc=com
ckanext.ldap.email = mail
ckanext.ldap.auth.password = password
ckanext.ldap.auth.method = SIMPLE

We can now integrate ckan with our LDAP.

Thanks.-
