### ISSUE TITLE
String formatting following CKAN guidelines

### ISSUE THREAD

**Issue by idgserpro** [NaturalHistoryMuseum/ckanext-ldap#8]
https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/6a990f503906656e4e9ddc4626bc973134a31d9d/ckanext/ldap/plugin.py#L98 and https://github.com/NaturalHistoryMuseum/ckanext-ldap/blob/41d7c7803917fd31649c48b904af1d8b7258af15/ckanext/ldap/controllers/user.py#L259 both have a string formatting that doesn't follow [CKAN guidelines](http://docs.ckan.org/en/latest/contributing/python.html#string-formatting). That's not an issue _per se_ but we're having problems when trying to use Python 2.6 in CentOS - Red Hat machines.

**Comment by alycejenni** [comment]
These strings now use numbers instead of keywords, so I hope that either this fixes the issue or you found another workaround. Please reopen this issue if it's still a problem.
