### ISSUE TITLE
/user/edit/{user} should be blocked

### ISSUE THREAD

**Issue by frafra** [NaturalHistoryMuseum/ckanext-ldap#84]
**Description**
It looks like users can alter their password and email address. I do not think that should be allowed when LDAP is used.

**Your Setup**
 - CKAN version: 2.9.x

**Comment by jrdh** [comment]
I think this should be possible by setting `ckanext.ldap.prevent_edits` in your config (https://github.com/NaturalHistoryMuseum/ckanext-ldap#other-options)?
